---
# Playbook to install mesos-dns services on a Mesos master node

- name: ensure git is present (apt)
  apt: name=git state=present cache_valid_time=3600 update_cache=yes
  when: ansible_pkg_mgr == 'apt'

- name: ensure git is present (yum)
  yum: name=git state=present update_cache=yes
  when: ansible_pkg_mgr == 'yum'

#- name: Checking prerequisite packages
#  apt: name=git-core state=present
#  sudo: yes

- name: Checking for Go binaries
  command: test -x go/bin/go
  register: go_installed
  ignore_errors: True

- name: Installing Go
  shell: curl -s https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz | tar xzf -
  args:
    chdir: "{{ ansible_env.HOME }}"
  environment: "{{proxy_env}}"
  when: go_installed|failed

- name: Checking for mesos-dns binaries
  command: test -x pkg/bin/mesos-dns
  register: mdns_installed
  ignore_errors: True

- name: Creates directory
  file: path="{{ ansible_env.HOME }}/pkg" state=directory

- name: Building mesos-dns binaries
  shell: "{{ ansible_env.HOME }}/go/bin/go get github.com/miekg/dns github.com/mesosphere/mesos-dns"
  args: 
   chdir: "{{ ansible_env.HOME }}"
  environment:
    http_proxy: http://gateway.ad.renci.org:8080/                                                   
    https_proxy: http://gateway.ad.renci.org:8080/    
    PATH: "{{ ansible_env.HOME }}/go/bin:/usr/local/bin:/usr/bin:/bin"
    GOPATH: "{{ ansible_env.HOME }}/pkg"
    GOROOT: "{{ ansible_env.HOME }}/go"
  when: mdns_installed|failed

#- name: Building mesos-dns binaries
#  shell: mkdir -p pkg && ~/go/bin/go get github.com/miekg/dns github.com/mesosphere/mesos-dns
#  shell: mkdir -p pkg && go get github.com/miekg/dns github.com/mesosphere/mesos-dns
#  shell: 
#  environment:
#    PATH: "{{ ansible_env.HOME }}/go/bin:/usr/local/bin:/usr/bin:/bin"
#    GOPATH: "{{ ansible_env.HOME }}/pkg"
#    GOROOT: "{{ ansible_env.HOME }}/go"
#  when: mdns_installed|failed

#TODO(jdef) once mesos-dns supports ZK detection we can check for /etc/mesos/zk

- name: Examining host IP configuration
  shell: ip -o -f inet addr show
           $(ip route | grep -e ^default.via | sed -e 's/.*dev //g') |
           head -1 | awk '{ print $4; }' | cut -f1 -d/
  register: servicehost

- set_fact:
    mesos_master: "{{ servicehost.stdout }}"

- name: Configuring mesos-dns
  template: src=config.json.j2 dest={{ ansible_env.HOME }}/mesos-dns-config.json mode=0644

#- name: Pushing mesos-dns artifacts to shared storage
#  shell: hdfs dfs -put -f pkg/bin/mesos-dns mesos-dns-config.json /
#  shell: cp -r pkg/bin/mesos-dns mesos-dns-config.json /projects/stars/stack/v2/mesos-dns

- name: Examining known slaves
  register: selected_slave
  shell: >
    mesos state | sed -n -e '/^    "slaves":.*$/,/^    \]/{/"hostname":/p}' | sed -e 's/^.*hostname": "\([^"]\+\)",.*$/\1/g' | sort | head -1

- name: Generating Marathon deployment descriptor
  template: src=mesos-dns.json.j2 dest={{ ansible_env.HOME }}/mesos-dns-app.json mode=0644

- name: Updating mesos-dns application deployment in Marathon
  shell: >
    curl -s -XPOST -H"Content-Type: application/json" http://{{ mesos_master }}:8080/v2/apps -d@mesos-dns-app.json
