galaxy_info:
  author: scox
  description: Ansible playbook for installing Stars on CentOS/Debian Linux
  license: BSD

  platforms:
  - name: EL
    versions:
     - 6
  - name: Ubuntu
    versions:
     - trusty

  galaxy_tags:
    - cloud
    - system



