---

# file: masters.yml
- hosts: masters
  user: evryscope
  become: true
  become_user: root
  roles:
    - { role: common,    tags: "common" }
    - { role: python,    tags: "python" }
    - { role: zookeeper, tags: "zookeeper" }
    - { role: mesos,     tags: "mesos" }
    - { role: marathon,  tags: "marathon" }
    - { role: mesos-dns, tags: "mesos-dns" }
    - { role: spark,     tags: "spark" }
    - { role: jenkins,   tags: "jenkins" }