# Main playbook.

---
- name: apply common configuration to all nodes
  hosts:  all
  user:   evryscope
  become: true
  become_user: root
  roles:
    - common
    - docker
    - { role: maven, tags: "maven" }
    - { role: java-se, java_variant: jre8, tags: "java" }

- include: masters.yml
- include: workers.yml
#- include: webservers.yml
