---
# file: workers.yml
- hosts: workers
  user: evryscope
  become: true
  become_user: root
  roles:
    - common
    - { role: mesos, tags="mesos" }
    - { role: spark, spark_version: "2.1.0", spark_cache_dir: "/opt", tags: "spark" }